  
name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.BOOKAPIDEPLOY }}
        APP_NAME: ${{ 'bookapi11' }}
      run: |
        cd ./
        docker login --username=fannanmajda123@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
